sudo: required
dist: trusty
services:
- docker
install:
- openssl aes-256-cbc -K $encrypted_414eb7c7e966_key -iv $encrypted_414eb7c7e966_iv -in .repo_key.gpg.enc -out .repo_key.gpg -d
- 'echo "Prospectus: $GITHUB_CREDS" >> .octoauth.yml'
- gpg --import < .repo_key.gpg
- sudo chown root:root .
script: make docker-build
deploy:
  provider: script
  script: make docker-upload || travis_terminate 1
  skip_cleanup: true
  on:
    branch: master
notifications:
  email: false
  slack:
    secure: ZeAmoPGNeFKQLN0VHFXlGVZ+rY8Itmg3K6/F2ug2GJy7/ohK4l3te5okkm/EE+qqMQYFZorky5JmiEYtZfQKGCvBEf5Ag5+bxYRnzeCuvHvmXt4w4MHjq7QhykaTLnwtPDa/AR/qgyOIH/asbOZ0+ntvViCAh29eK4f/5xLcRZJajF/ocaeHy33WwpeMEZnZ8L/JwdoHUA9XZ/Nzq3DrFTkIxZHwB/Sh3rABquIr7kaofEcp7hOt7hMzsA4+nTWuZ5zobCjB1EEl0DHJmXOMxiqeYuJY9kj9uTMsOLXVsNfTVkBM1YjuQGJjC9mX8JWbqL6XpuDKf/nBVN0ignjT+1AZ8T3nrp3yk6YFx0llMHl3RwZsnT9e+06s8kG493rnvz8lnDd/TDwbOFfTLUhzKymBz7do3WAfu3rQLJhbOb8nzt4UbZ1ZfPLcQeNy+heAz0seywV3FZrRjiCg51fCPtvjJuWcGtO4WnembtzG2Rq8R9ACM/laZAXJzp16XiQ9E8CmA4nC1ANYvmaPWFVePaKm9clt/QAK3kYUohnYTtbOMEyyzSoUnHoeUJuEJDiE6yfxBqGj51flpXM5UmPRfO2l8SBw+DyKoSnd6Xr03XNOB7zGx9qB8yY56DCAFkybMaDdcZ8QSHWfMEhzrNsb9hecB9lHP9T6vVHDVouBcss=
env:
  global:
  - secure: ZzDhunxANc84iLm0lrsYhKpr0QDQdBQCU2+MyqZ+9aW+dBWRsqwEbJePmM5C/lcUOae0Jvz84D3Ot3oYDjxN523L2Fq/TSU08FJD06yZkj6EmdWS+71701oVPJTswYj5l8akcJ3bcibPzZ4WMPM5JQT8f0hJG9Uh9jM09ruH8Z+s1ew70Oln2JkptPd1z3owQ51L2MBqiiwNC69aIycDvVF+tlXx23b11ZoUMBhdseIKkMSQmJRAJ76twsGs0yUlal+A/I7yw+43kmBjauBSyUh1HwxLSqhakc5PA1VQ1E5VLh7XcOO/S8l71v+a39xT5mO8dl/NNus4euKUIXoatPA4YFM6EasHiJMoXdFML7D8iPhQgmvrQSbKSASNU+EkMI7giJQkwjo2I1vNjyQtheRNm+NJdzmT0RK/sOVMLpRWKJlUaurmL5R+Gtu2k5WV5Fu8seGmCk3MmLN+CQP+yXnH3vIiQ+L4fZ7WCLAJb9yZ8jCPJPcVSs8Oz4rzYgNDq2F6iD/Fakic2fSilmt81A4oVz91hhKcPZkYXNOQW1K/9et5B08rKKZp0/mCu1GDqlNLad1Cc4sARj5kUximkI7K8gU3r6y0ugLFw1Ojo/XW1ZYAYu3IMLhkmmC21neIjG1+gGuCzV7tlLyt39bcJhnOh6bDMi2bMXWvBEfR5pU=
  - secure: mOS+4A20CeCLX7piJIve26TAnBtjRehpfTzfrYbLT7VG1eA2pc8H9V4QgMMFJYRqa2KsCx2sZaSyVQoSAdYfkyFfzIIiIq9EclWkwv8zl/E36Fhf0Qzulla7SbJ/XyZ1edNjBkCF1GUR87azianZBWj3MdWsgRfoZg+HlPsslfvyz04DEVE+nZfbnG0/GSskZRcYOQ3oaNk+iQFReoych2BwOHAOQcoPjmsPyg7ShVhPb/7aQZS9yZAQcjE6K7IqC2ioMRlyiEvAZYfCbjjoWuvJPXm70hNK8tH80E/Ej6vso38tKCIPu7IQRnRgtDCL57/8Uotgsh2tmiOh3DD47rn4OYrCSN4rzdTDrrF7b24ScvETwfxdPobMtvMIr4GZPgnMoms2Yqoh19iH1aLxUFChSKmK449gJEzxv9i1OrFXMw/3cxlBCIWliPYTQu6liGU+TRDYYoTBkWLsiH0AusdR2xTZOAziinq9Uht1fdxUalzqQ1vM7YG68D/ddBsQj2UpV/JxFg//dwqR1//PpEAk5E+NZYmS6ZWeqJ+2oogBqMcaVVaOJMlBT8GBWMQUd4aQTdGyxadR+TI7D7I2tqWJn0UWbALf4LJBK8MPL8CpmvtbYUh8YXfoiG1x+V36EbVJW2zg5O2h9LTsMhUvStCFWfsaOumLeZEyMUWxFF4=
