repo_name: amylum
bucket: amylum-repo
region: us-east-1
makepkg_flags: --clean --force --nodeps
targets:
  - x86_64
  - aarch64
key: F32EF721720E464B25C21F80C31B697E9E98B759
sign_db: true
sign_packages: true
template_dir: templates
template_params:
  email: repo@lesaker.org
  repo_name: amylum
  repo_source: https://github.com/amylum
  repo_domain: repo.scrtybybscrty.org
  repo_key_id: F32EF721720E464B25C21F80C31B697E9E98B759
  repo_gpg_urls:
    'My blog': https://blog.akerl.org/keys/arch-repo.gpg
    GitHub: https://github.com/akerl/blog/blob/main/static/keys/arch-repo.gpg
