bucket: amylum-repo
region: us-east-1
makepkg_flags: --clean
key: 917CA18E2FDC46C33094B4B7030CB6B34D642144
sign_db: true
sign_packages: true
template_dir: templates
template_params:
  email: me@lesaker.org
  repo_name: amylum
  repo_source: https://github.com/amylum
  repo_domain: repo.scrtybybscrty.org
  repo_key_id: nothin
  repo_gpg_urls:
    blah: crap
    what: nope
